INSERT INTO DDD (Region, State, DDDCode) VALUES ('Centro-Oeste', 'DF', 61);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Centro-Oeste', 'GO', 62);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Centro-Oeste', 'GO', 64);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Centro-Oeste', 'MT', 65);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Centro-Oeste', 'MT', 66);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Centro-Oeste', 'MS', 67);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'AL', 82);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'BA', 71);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'BA', 73);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'BA', 74);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'BA', 75);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'BA', 77);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'CE', 85);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'CE', 88);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'MA', 98);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'MA', 99);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'PB', 83);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'PE', 81);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'PE', 87);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'PI', 86);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'PI', 89);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'RN', 84);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Nordeste', 'SE', 79);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'AC', 68);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'AP', 96);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'AM', 92);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'AM', 97);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'PA', 91);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'PA', 93);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'PA', 94);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'RO', 69);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'RR', 95);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Norte', 'RO', 63);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'ES', 27);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'ES', 28);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'MG', 31);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'MG', 32);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'MG', 33);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'MG', 34);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'MG', 35);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'MG', 37);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'MG', 38);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'RJ', 21);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'RJ', 22);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'RJ', 24);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 11);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 12);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 13);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 14);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 15);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 16);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 17);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 18);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sudeste', 'SP', 19);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'PR', 41);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'PR', 42);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'PR', 43);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'PR', 44);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'PR', 45);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'PR', 46);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'RS', 51);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'RS', 53);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'RS', 54);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'RS', 55);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'SC', 47);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'SC', 48);
INSERT INTO DDD (Region, State, DDDCode) VALUES ('Sul', 'SC', 49);

INSERT INTO PhonePlanType (Description) VALUES ('Controle');
INSERT INTO PhonePlanType (Description) VALUES ('Pós-pago');
INSERT INTO PhonePlanType (Description) VALUES ('Pré-pago');

INSERT INTO TelephoneOperator (Name) VALUES ('Claro');
INSERT INTO TelephoneOperator (Name) VALUES ('Vivo');
INSERT INTO TelephoneOperator (Name) VALUES ('Algar Telecom');
INSERT INTO TelephoneOperator (Name) VALUES ('TIM');
INSERT INTO TelephoneOperator (Name) VALUES ('Nextel');
INSERT INTO TelephoneOperator (Name) VALUES ('Oi');

